//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aakar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apartment()
        {
            this.comments = new HashSet<comment>();
            this.rentals = new HashSet<rental>();
            this.rom_images = new HashSet<rom_images>();
        }
    
        public int id { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string floor { get; set; }
        public Nullable<int> room_count { get; set; }
        public Nullable<int> price { get; set; }
        public string details { get; set; }
        public Nullable<bool> available { get; set; }
        public string kiswa { get; set; }
        public string main_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rental> rentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rom_images> rom_images { get; set; }
    }
}
