//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aakar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AakarEntities1 : DbContext
    {
        public AakarEntities1()
            : base("name=AakarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartment> apartments { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<rental> rentals { get; set; }
        public virtual DbSet<rom_images> rom_images { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
