//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aakar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> apartment_id { get; set; }
        public Nullable<System.DateTime> rental_date { get; set; }
        public string rental_period { get; set; }
        public string price { get; set; }
    
        public virtual apartment apartment { get; set; }
        public virtual user user { get; set; }
    }
}
